# This is a copy of
# https://github.com/mdn/content/blob/main/.github/workflows/pr-check_duplicates.yml
name: Check for duplicates

on:
  pull_request:
    branches:
      - main
    paths:
      - files/**/index.*
      - .github/workflows/pr-check_duplicates.yml

jobs:
  check_duplicates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for duplicates
        run: |
          find files -name 'index.*' -type f -printf '%h\n' | sort | uniq -d > dupes.txt
          cat dupes.txt
          [ ! -s dupes.txt ]
